#!/bin/sh
# Generated by agentp 2026.10.1 from the Contoso platform definition. Do not edit by hand.
# Run as root (Intune macOS shell script, Jamf policy, or configuration management). Copilot rejects
# managed files that are symlinks, not owned by root, or group/world-writable.
set -eu
install -d -o root -g wheel -m 0755 "$(dirname '/Library/Application Support/GitHubCopilot/managed-settings.json')" 2>/dev/null || install -d -o root -g root -m 0755 "$(dirname '/Library/Application Support/GitHubCopilot/managed-settings.json')"
cat > '/Library/Application Support/GitHubCopilot/managed-settings.json.tmp' <<'AGENTP_EOF'
{
  "permissions": {
    "disableBypassPermissionsMode": "disable",
    "deny": [
      "Read(~/.ssh/**)",
      "Read(~/.aws/**)",
      "Read(~/.azure/**)",
      "Edit(//etc/**)"
    ]
  },
  "remoteControl": {
    "mode": "requireSSO",
    "githubDotComOrganizations": [
      "contoso"
    ]
  },
  "sandbox": {
    "enabled": true,
    "failIfUnavailable": true,
    "allowBypass": false,
    "addCurrentWorkingDirectory": false,
    "sandboxMcpServers": true,
    "sandboxLspServers": true,
    "gitAuth": false,
    "ghAuth": false,
    "allowDevToolAccess": false,
    "userPolicy": {
      "filesystem": {
        "readwritePaths": [
          "/home",
          "/Users",
          "C:\\Users",
          "C:\\src"
        ],
        "readonlyPaths": [
          "/opt/tools",
          "C:\\Tools"
        ],
        "deniedPaths": [
          "/etc/ssh",
          "C:\\Windows\\System32\\config"
        ]
      },
      "network": {
        "allowLocalNetwork": false,
        "allowedHosts": [
          "github.com",
          "*.githubusercontent.com",
          "*.contoso.com"
        ],
        "blockedHosts": [
          "pastebin.com"
        ],
        "proxy": {
          "url": "http://egress.contoso.com:3128"
        }
      },
      "seatbelt": {
        "keychainAccess": false
      }
    }
  },
  "policyHelper": {
    "path": "C:\\Program Files\\Contoso\\copilot-policy.exe",
    "args": [
      "--json"
    ],
    "timeoutMs": 2000,
    "refreshIntervalMs": 3600000
  },
  "forceLoginOrgs": [
    "contoso"
  ]
}
AGENTP_EOF
chown root "/Library/Application Support/GitHubCopilot/managed-settings.json.tmp" && chmod 0644 "/Library/Application Support/GitHubCopilot/managed-settings.json.tmp" && mv -f "/Library/Application Support/GitHubCopilot/managed-settings.json.tmp" "/Library/Application Support/GitHubCopilot/managed-settings.json"
install -d -o root -g wheel -m 0755 "$(dirname '/etc/github-copilot/policy.d/00-agent-platform.json')" 2>/dev/null || install -d -o root -g root -m 0755 "$(dirname '/etc/github-copilot/policy.d/00-agent-platform.json')"
cat > '/etc/github-copilot/policy.d/00-agent-platform.json.tmp' <<'AGENTP_EOF'
{
  "version": 1,
  "hooks": {
    "preToolUse": [
      {
        "type": "command",
        "exec": "curl.exe",
        "args": [
          "-sS",
          "--fail",
          "--max-time",
          "4",
          "--variable",
          "%AGENTP_HOOK_TOKEN",
          "--expand-header",
          "Authorization: Bearer {{AGENTP_HOOK_TOKEN}}",
          "-H",
          "Content-Type: application/json",
          "-H",
          "X-Agentp-Event: preToolUse",
          "-H",
          "X-Agentp-Source: policy-hook",
          "--data-binary",
          "@-",
          "https://agents.contoso.com/hooks?decide=1"
        ],
        "timeoutSec": 5
      }
    ],
    "postToolUse": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "postToolUse",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "userPromptSubmitted": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "userPromptSubmitted",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "sessionStart": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "sessionStart",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "postToolUseFailure": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "postToolUseFailure",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "subagentStart": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "subagentStart",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "subagentStop": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "subagentStop",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "agentStop": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "agentStop",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "errorOccurred": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "errorOccurred",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "preCompact": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "preCompact",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ],
    "sessionEnd": [
      {
        "type": "http",
        "url": "https://agents.contoso.com/hooks",
        "headers": {
          "X-Agentp-Event": "sessionEnd",
          "X-Agentp-Source": "policy-hook",
          "Authorization": "Bearer ${AGENTP_HOOK_TOKEN}"
        },
        "allowedEnvVars": [
          "AGENTP_HOOK_TOKEN"
        ],
        "timeoutSec": 5
      }
    ]
  }
}
AGENTP_EOF
chown root "/etc/github-copilot/policy.d/00-agent-platform.json.tmp" && chmod 0644 "/etc/github-copilot/policy.d/00-agent-platform.json.tmp" && mv -f "/etc/github-copilot/policy.d/00-agent-platform.json.tmp" "/etc/github-copilot/policy.d/00-agent-platform.json"
