/// Rendering a platform { } into every file GitHub, the clients and gh-aw read.
///
/// Output is a tree of repositories, each committed and pushed as-is by the deploy workflow:
///
///     .github-private/            enterprise "Configuration source": managed settings, teams, agents
///     copilot-plugins/            the marketplace: plugins carrying skills, agents, standards, MCP, hooks
///     repo-baseline/              synced into every repository: instructions, AGENTS.md, .github/hooks
///     agentic-workflows/          gh-aw workflows, shared governance import, gh aw env defaults
///     endpoints/                  the platform host's static content: v0.1 MCP registry
///     workstation/                file-based + MDM managed settings and machine-wide policy hooks
///     github/                     REST bodies for rulesets, content exclusion, cloud agent (applied by `agentp apply`)
///     platform.lock.json          version + content hash of everything above
module AgentPlatform.Render

open System
open System.IO
open System.Security.Cryptography
open System.Text
open System.Text.Json.Nodes
open AgentPlatform.Json
open AgentPlatform.Policy
open AgentPlatform.HookEvents
open AgentPlatform.Hooks
open AgentPlatform.Mcp
open AgentPlatform.Standards
open AgentPlatform.Plugins
open AgentPlatform.Agents
open AgentPlatform.Governance
open AgentPlatform.Platform

type File = { Path: string; Content: string }

let private file path content = { Path = path; Content = content }

let private banner (p: Platform) = $"Generated by agentp {p.Version} from the {p.Name} platform definition. Do not edit by hand."

// ---------------------------------------------------------------------------
// Agent profiles
// ---------------------------------------------------------------------------

let private yamlString (s: string) = "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\""

/// The `.agent.md` profile. One file serves every surface that reads custom agents.
let profile (p: Platform) (a: Agent) =
    let servers = serversNamed p a.Mcp
    let tools =
        a.Tools @ (a.Mcp |> List.map (fun m -> McpTools(m, "*")))
        |> List.distinct
        |> List.map (fun t -> yamlString t.Text)
        |> String.concat ", "
    let standards = standardsNamed p a.Standards
    let lines = [
        "---"
        $"name: {a.Name}"
        $"description: {yamlString a.Description}"
        if tools <> "" then $"tools: [{tools}]"
        match a.Model with Some m -> $"model: {m}" | None -> ()
        if a.OnlyWhenAsked then "disable-model-invocation: true"
        if a.NotUserSelectable then "user-invocable: false"
        yield! agentProfileYaml servers
        "metadata:"
        match a.Owner with Some o -> $"  owner: {yamlString o}" | None -> ()
        let governedBy = p.Organization + "/.github-private"
        $"  governed-by: {yamlString governedBy}"
        $"  platform-version: {yamlString p.Version}"
        if not a.Evals.IsEmpty then
            let ids = a.Evals |> List.map _.Id |> String.concat ","
            $"  evals: {yamlString ids}"
        "---"
        ""
        dedent a.Instructions
        for s in standards do
            ""
            $"## {s.Title}"
            ""
            yield! s.Rules |> List.map (fun r -> $"- {r}")
        if not a.Forbidden.IsEmpty then
            ""
            "Never read, search for, quote or summarise anything about: " + String.Join(", ", a.Forbidden) + "."
    ]
    String.concat "\n" lines + "\n"

// ---------------------------------------------------------------------------
// Hooks: one rule set, rendered for every place hooks are loaded
// ---------------------------------------------------------------------------

/// How each kind of hook carries the platform token (when `hookTokenFrom` is set):
///   exec curl.exe  curl's own `--variable %NAME --expand-header` reads the environment (no shell needed)
///   bash curl      "$NAME" in the command
///   http hook      `allowedEnvVars` + ${NAME} in the header value (hooks-reference "HTTP hooks")
let private curlAuthArgs (p: Platform) =
    (match p.HostCaPath with
     // Schannel cannot check revocation for a private CA, so it is skipped for that CA only.
     | Some pem -> [ "--cacert"; pem; "--ssl-no-revoke" ]
     | None -> [])
    @ (match p.HookTokenVariable with
       | Some v -> [ "--variable"; $"%%{v}"; "--expand-header"; "Authorization: Bearer {{" + v + "}}" ]
       | None -> [])

let private bashAuth (p: Platform) =
    match p.HookTokenVariable with
    | Some v -> $" -H \"Authorization: Bearer ${{{v}}}\""
    | None -> ""

/// The deciding hook, with nothing installed and no shell start-up.
///   machine / plugin layers  `exec curl.exe` - runs the executable directly, no shell at all
///                            (`exec` is CLI-only and cannot be combined with bash/powershell)
///   repository layer         `bash` curl - the only field cloud agent honours, also fine on Linux/macOS
/// `--fail` makes an unreachable or erroring service a non-zero exit, and a non-zero preToolUse
/// command hook DENIES (hooks-reference "Exit codes for command hooks": fail-closed).
let private decidingCommand (p: Platform) (event: HookEvent) (source: string) (forRepository: bool) =
    let url = $"{hooksUrl p}?decide=1"
    if forRepository then
        let bash =
            $"curl -sS --fail --max-time 4{bashAuth p} -H 'Content-Type: application/json' -H 'X-Agentp-Event: {event.Name}' -H 'X-Agentp-Source: {source}' --data-binary @- '{url}' || exit 2"
        obj [ "type", Some(str "command"); "bash", Some(str bash); "timeoutSec", Some(num 5) ]
    else
        obj [
            "type", Some(str "command")
            "exec", Some(str "curl.exe")
            "args",
            Some(
                strs (
                    [ "-sS"; "--fail"; "--max-time"; "4" ]
                    @ curlAuthArgs p
                    @ [
                        "-H"; "Content-Type: application/json"
                        "-H"; $"X-Agentp-Event: {event.Name}"
                        "-H"; $"X-Agentp-Source: {source}"
                        "--data-binary"; "@-"
                        url
                    ]
                )
            )
            "timeoutSec", Some(num 5)
        ]

/// Capture: an HTTP hook. The runtime POSTs the payload itself - no process starts at all.
let private httpHook (p: Platform) (event: HookEvent) (source: string) =
    let auth, allowed =
        match p.HookTokenVariable with
        | Some v -> [ "Authorization", str ("Bearer ${" + v + "}") ], Some(strs [ v ])
        | None -> [], None
    obj [
        "type", Some(str "http")
        "url", Some(str (hooksUrl p))
        "headers", Some(objOf ([ "X-Agentp-Event", str event.Name; "X-Agentp-Source", str source ] @ auth))
        "allowedEnvVars", allowed
        "timeoutSec", Some(num 5)
    ]

/// A trailing transfer that cannot fail on Windows, so the exit code reports it rather than the collector call.
let private alwaysSucceeds = [ "--next"; "-s"; "-o"; "NUL"; "file:///C:/Windows/win.ini" ]

/// Capture over curl, for hosts on internal networks. Fail-OPEN: no `|| exit 2`, and non-deciding
/// events ignore non-zero exits, so a collector outage never blocks anyone.
let private curlCapture (p: Platform) (event: HookEvent) (source: string) (forRepository: bool) =
    let url = hooksUrl p
    if forRepository then
        let bash =
            $"curl -sS --max-time 4{bashAuth p} -H 'Content-Type: application/json' -H 'X-Agentp-Event: {event.Name}' -H 'X-Agentp-Source: {source}' --data-binary @- '{url}' >/dev/null || true"
        obj [ "type", Some(str "command"); "bash", Some(str bash); "timeoutSec", Some(num 5) ]
    else
        obj [
            "type", Some(str "command")
            "exec", Some(str "curl.exe")
            // curl exits with the LAST transfer's result. A non-zero preToolUse command hook DENIES (hooks-reference
            // "Exit codes for command hooks"), so a capture-only hook ends with a local file read that always succeeds:
            // an unreachable collector can never block a tool call. Deciding hooks (decidingCommand) keep --fail.
            "args", Some(strs ([ "-sS"; "--max-time"; "4"; "-o"; "NUL" ] @ curlAuthArgs p @ [ "-H"; "Content-Type: application/json"; "-H"; $"X-Agentp-Event: {event.Name}"; "-H"; $"X-Agentp-Source: {source}"; "--data-binary"; "@-"; url ] @ alwaysSucceeds))
            "timeoutSec", Some(num 5)
        ]

/// A hooks.json for one layer. Events a rule can decide go through a fail-closed command;
/// everything else is captured the way the platform's hooks { } chose (HTTP hooks by default).
let hooksJson (p: Platform) (source: string) (forCloudAgent: bool) =
    let h = p.Hooks
    let deciding = decidingEvents h |> Set.ofList
    let events =
        eventsFor h
        |> List.filter (fun e -> not forCloudAgent || e.FiresInCloudAgent)
    let entries =
        events
        |> List.map (fun e ->
            let entry =
                if deciding.Contains e then decidingCommand p e source forCloudAgent
                else
                    match h.CaptureVia with
                    | HttpHooks -> httpHook p e source
                    | CurlCommands -> curlCapture p e source forCloudAgent
            match matcherFor h e with
            | Some m when deciding.Contains e -> (entry :?> JsonObject)["matcher"] <- str m
            | _ -> ()
            e.Name, arr [ entry ])
    objOf [ "version", num 1; "hooks", objOf entries ]

/// The rule set itself, as data, so the daemon can load it without the F# definition.
let rulesJson (p: Platform) =
    let rec cond (c: Condition) : JsonNode =
        match c with
        | ToolIs names -> objOf [ "toolIs", strs names ]
        | ArgsMatch r -> objOf [ "argsMatch", str r ]
        | CommandStartsWith s -> objOf [ "commandStartsWith", str s ]
        | PathMatches g -> objOf [ "pathMatches", str g ]
        | PromptContains s -> objOf [ "promptContains", str s ]
        | OnSurface ss -> objOf [ "onSurface", strs (ss |> List.map _.Text) ]
        | All cs -> objOf [ "all", (cs |> List.map cond |> arr) ]
        | AnyOf cs -> objOf [ "anyOf", (cs |> List.map cond |> arr) ]
        | Not c -> objOf [ "not", cond c ]
        | Always -> objOf [ "always", bool true ]
    let rec action =
        function
        | DryRun a -> objOf [ "dryRun", action a ]
        | Block r -> objOf [ "block", str r ]
        | RequireApproval r -> objOf [ "requireApproval", str r ]
        | Approve -> objOf [ "approve", bool true ]
        | AddContext t -> objOf [ "addContext", str t ]
        | KeepGoing t -> objOf [ "keepGoing", str t ]
        | Record -> objOf [ "record", bool true ]
    objOf [
        "version", str p.Version
        "rules",
        p.Hooks.Rules
        |> List.map (fun r ->
            obj [
                "name", Some(str r.Name)
                "description", (if r.Description = "" then None else Some(str r.Description))
                "events", Some(strs (r.Events |> List.map _.Name))
                "when", Some(cond r.When)
                "then", Some(action r.Then)
                "onFailure", Some(str (match r.OnFailure with FailClosed -> "closed" | FailOpen -> "open"))
            ])
        |> arr
        "capture",
        match p.Hooks.Capture with
        | Some c -> objOf [ "events", strs (c.Events |> List.map _.Name); "includeContent", bool c.IncludeContent ]
        | None -> objOf [ "events", strs [] ]
    ]

// ---------------------------------------------------------------------------
// .github-private
// ---------------------------------------------------------------------------

let githubPrivate (p: Platform) = [
    let pol = resolvedPolicy p
    file ".github-private/copilot/managed-settings.json" (render (toJson (forServer pol)))
    if not p.Teams.IsEmpty then
        // Enterprise team slugs carry an `ent:` prefix (teams-in-an-enterprise.md) while the team-mapping docs show
        // bare slugs; both spellings are listed so the mapping matches whichever the server compares.
        let bothForms (slug: string) = if slug.StartsWith "ent:" then [ slug.Substring 4; slug ] else [ slug; "ent:" + slug ]
        file ".github-private/copilot/team-mappings.json" (p.Teams |> List.map (fun t -> $"{t.Name}.json", strs (t.EnterpriseTeams |> List.collect bothForms)) |> objOf |> render)
    for t in p.Teams do
        file $".github-private/copilot/teams/{t.Name}.json" (render (toJson (forServer t.Policy)))
    for a in p.Agents do
        file $".github-private/agents/{a.Name}.md" (profile p a)
    for s in p.OrganizationSkills do
        file $".github-private/skills/{s.Name}/SKILL.md" (skillMarkdown s)
    match p.AdminTeam with
    | Some team -> file ".github-private/CODEOWNERS" ("* @{org}/{team}\n".Replace("{org}", p.Organization).Replace("{team}", team))
    | None -> ()
    file ".github-private/README.md" (
        $"# {p.Organization}/.github-private\n\n{banner p}\n\n"
        + "This repository is the enterprise **Configuration source** (Enterprise > AI controls > Agents). "
        + "GitHub validates `copilot/` on every push and lists problems under \"Copilot settings validation\".\n\n"
        + "| Path | Governs |\n| --- | --- |\n"
        + "| `copilot/managed-settings.json` | every Copilot user licensed through the enterprise, on every supported client |\n"
        + "| `copilot/team-mappings.json`, `copilot/teams/*.json` | overrides of overridable keys for enterprise teams |\n"
        + "| `agents/*.md` | enterprise custom agents in every repository |\n")
]

// ---------------------------------------------------------------------------
// The marketplace
// ---------------------------------------------------------------------------

let marketplaceFiles (p: Platform) = [
    let m = marketplace p
    file "copilot-plugins/.github/plugin/marketplace.json" (render (marketplaceJson m))
    file "copilot-plugins/README.md" $"# {m.Name}\n\n{banner p}\n\nEvery plugin here is installed on every Copilot client by `enabledPlugins` in enterprise managed settings, and this is the only marketplace `strictKnownMarketplaces` allows.\n"
    for pl in m.Plugins do
        let root = $"copilot-plugins/plugins/{pl.Name}"
        let servers = serversNamed p pl.Mcp
        file $"{root}/plugin.json" (render (pluginJson pl (not servers.IsEmpty)))
        for s in pl.Skills do
            file $"{root}/skills/{s.Name}/SKILL.md" (skillMarkdown s)
            for path, content in s.Files do
                file $"{root}/skills/{s.Name}/{path}" content
        for s in standardsNamed p pl.Standards do
            let sk = standardAsSkill s
            file $"{root}/skills/{sk.Name}/SKILL.md" (skillMarkdown sk)
        for name in pl.Agents do
            match agentNamed p name with
            | Some a -> file $"{root}/agents/{a.Name}.agent.md" (profile p a)
            | None -> ()
        if not servers.IsEmpty then
            file $"{root}/.mcp.json" (render (pluginMcpJson servers))
        if pl.CarriesHooks then
            file $"{root}/hooks.json" (render (hooksJson p $"plugin:{pl.Name}" false))
            file $"{root}/hook-rules.json" (render (rulesJson p))
]

// ---------------------------------------------------------------------------
// Every repository
// ---------------------------------------------------------------------------

let repoBaseline (p: Platform) = [
    file "repo-baseline/.github/copilot-instructions.md" (repositoryInstructions p.Name p.Standards)
    for s in p.Standards |> List.filter (fun s -> not s.AppliesTo.IsEmpty) do
        file $"repo-baseline/.github/instructions/{s.Name}.instructions.md" (instructionsFile s)
    file "repo-baseline/AGENTS.md" (agentsMd p.Name p.Standards)
    // The only hooks cloud agent ever loads; also honoured by the CLI and VS Code in this repo. Omitted while hooks
    // are piloted (enforceHooksOnlyFor): a repository file would reach everyone who works in the repository.
    if p.HookPilotTeams.IsEmpty then
        file $"repo-baseline/.github/hooks/{p.Organization}-platform.json" (render (hooksJson p "repo-hook" true))
    let cloudMcp = p.Mcp.Servers |> List.filter (fun s -> p.Agents |> List.exists (fun a -> List.contains s.Key a.Mcp))
    file "repo-baseline/.github/copilot/cloud-agent-mcp.json" (render (cloudAgentConfig cloudMcp))
]

// ---------------------------------------------------------------------------
// gh-aw
// ---------------------------------------------------------------------------

let private yamlList (xs: string list) = "[" + (xs |> List.map yamlString |> String.concat ", ") + "]"

/// gh-aw's built-in tool names (pkg/workflow/mcp_config_validation.go builtInToolNames).
/// Tracked by Drift ("gh-aw.builtin-tools") so a new reserved name is caught automatically.
let ghAwReservedToolNames = [
    "github"; "jira"; "playwright"; "agentic-workflows"; "cache-memory"; "drive-memory"; "comment-memory"; "repo-memory"
    "ledger"; "work-queue"; "bash"; "edit"; "web-fetch"; "web-search"; "linear"; "safety-prompt"; "timeout"; "startup-timeout"; "cli-proxy"
]

let workflowMarkdown (p: Platform) (w: Workflow) =
    let a = agentNamed p w.Agent |> Option.get
    let host = Uri(p.Host).Host
    let sb = StringBuilder()
    let line (s: string) = sb.Append(s).Append('\n') |> ignore
    line "---"
    line $"name: {yamlString w.Name}"
    line $"description: {yamlString w.Description}"
    line "on:"
    for t in w.On do
        match t with
        | Schedule s -> line $"  schedule: {yamlString s}"
        | PullRequestOpened -> line "  pull_request:"; line "    types: [opened, synchronize, reopened]"
        | IssueOpened -> line "  issues:"; line "    types: [opened]"
        | WorkflowFailed wfs -> line "  workflow_run:"; line $"    workflows: {yamlList wfs}"; line "    types: [completed]"; line "    branches: [main]"
        | Manually -> line "  workflow_dispatch:"
        | SlashCommand name -> line "  slash_command:"; line $"    name: {name}"
    if not (List.contains Manually w.On) then line "  workflow_dispatch:"
    line "permissions:"
    for r in w.Reads do line $"  {r}: read"
    line "  copilot-requests: write"
    line "engine:"
    line "  id: copilot"
    if w.CopilotSdk then line "  copilot-sdk: true"
    match a.Model with Some m -> line $"  model: {m}" | None -> ()
    line "strict: true"
    line $"timeout-minutes: {w.TimeoutMinutes}"
    match w.MaxAiCredits with Some c -> line $"max-ai-credits: {c}" | None -> ()
    line "network:"
    line "  allowed:"
    // An internal host is unreachable from GitHub-hosted runners (and gh-aw rejects it): leave it out.
    let platformHosts = if hostIsInternal p then [] else [ host ]
    for n in w.Network @ platformHosts |> List.distinct do line $"    - {yamlString n}"
    line "tools:"
    line "  github:"
    line $"    toolsets: {yamlList w.Toolsets}"
    if not w.Bash.IsEmpty then line $"  bash: {yamlList w.Bash}"
    if w.CanEdit then line "  edit:"
    let servers = serversNamed p a.Mcp |> List.filter (fun s -> match s.Transport with Remote _ -> true | _ -> (commandLine s).IsSome)
    if not servers.IsEmpty then
        line "mcp-servers:"
        for s in servers do
            // gh-aw reserves some names (github, jira, playwright, linear, ...) for first-class tools
            // with their own schema; custom servers must not collide with them.
            let key = if List.contains s.Key ghAwReservedToolNames then $"{p.Organization}-{s.Key}" else s.Key
            line $"  {key}:"
            match s.Transport, commandLine s with
            | Remote(url, _), _ ->
                line "    type: http"
                line $"    url: {yamlString url}"
                // gh-aw requires auth on remote servers: header secrets map to repository/org Actions secrets.
                let headers = s.Secrets |> List.filter _.Header
                if headers.IsEmpty then
                    line "    auth:"
                    line "      type: github-oidc"
                else
                    line "    headers:"
                    for h in headers do
                        let secret = "MCP_" + s.Key.ToUpperInvariant().Replace('-', '_') + "_" + h.Name.ToUpperInvariant().Replace('-', '_')
                        line $"      {h.Name}: \"${{{{ secrets.{secret} }}}}\""
            | _, Some(cmd, args) -> line "    type: stdio"; line $"    command: {yamlString cmd}"; line $"    args: {yamlList args}"
            | _ -> ()
            line $"    allowed: {yamlList s.Tools}"
    if not w.Plugins.IsEmpty then
        line "plugins:"
        for pl in w.Plugins do line $"  - {marketplaceRepo p}/plugins/{pl}@{p.MarketplaceRef}"
    line "safe-outputs:"
    for s in w.Writes do
        match s with
        | CreateIssue(prefix, labels, max) ->
            line "  create-issue:"; line $"    title-prefix: {yamlString prefix}"; line $"    labels: {yamlList labels}"; line $"    max: {max}"
        | AddComment max -> line "  add-comment:"; line $"    max: {max}"
        | AddLabels allowed -> line "  add-labels:"; line $"    allowed: {yamlList allowed}"
        | CreatePullRequest(prefix, draft) ->
            let draftText = if draft then "true" else "false"
            line "  create-pull-request:"; line $"    title-prefix: {yamlString prefix}"; line $"    draft: {draftText}"
        | ReviewPullRequest _ -> line "  submit-pull-request-review:"; line "    max: 1"; line "    allowed-events: [COMMENT, REQUEST_CHANGES]"
        | AssignToCopilot -> line "  assign-to-agent:"
        | Noop -> line "  noop:"
    line "imports:"
    line $"  - shared/{p.Organization}-governance.md"
    line $"  - .github/agents/{a.Name}.md"
    if not a.Evals.IsEmpty then
        line "evals:"
        for q in a.Evals do
            line $"  - id: {q.Id}"
            line $"    question: {yamlString q.Question}"
    match w.Graders with
    | [] -> ()
    | graders ->
        let custom = graders |> List.choose (function OperationalValue(n, d, u, s) -> Some(n, d, u, s) | _ -> None)
        if custom.IsEmpty then line "graders: {}"
        else
            line "graders:"
            for n, d, u, s in custom do
                line "  operational-value:"
                line $"    name: {yamlString n}"
                line $"    description: {yamlString d}"
                line $"    unit: {u}"
                line "    direction: higher_is_better"
                line "    script: |"
                for l in s.Trim().Split('\n') do line $"      {l.TrimEnd()}"
    if not w.Experiments.IsEmpty then
        line "experiments:"
        for x in w.Experiments do
            line $"  {x.Name}:"
            line $"    variants: {yamlList x.Variants}"
            line $"    metric: {yamlString x.Metric}"
            line $"    min_samples: {x.MinSamples}"
    line "---"
    line ""
    line $"# {w.Name}"
    line ""
    line (dedent w.Task)
    for x in w.Experiments do
        // gh-aw only authorises `{{#if experiments.<name> == '<variant>' }}` blocks in the prompt.
        for v in x.Variants do
            line ""
            line $"{{{{#if experiments.{x.Name} == '{v}' }}}}"
            line $"Work in a **{v}** way for this run."
            line "{{/if}}"
    sb.ToString()

let governanceImport (p: Platform) =
    let host = Uri(p.Host).Host
    let hostLine = if hostIsInternal p then "" else $"\n    - \"{host}\""
    $"""---
network:
  allowed:
    - "defaults"{hostLine}
---

<!--
{banner p}
Every {p.Name} agentic workflow imports this file. OTLP export is configured centrally (agentic-workflows/aw-defaults.yml
via `gh aw env update --scope org`), so no workflow can forget it; Copilot CLI inside the run exports to the same collector.
-->
"""

let agenticWorkflows (p: Platform) = [
    file $"agentic-workflows/.github/workflows/shared/{p.Organization}-governance.md" (governanceImport p)
    for w in p.Workflows do
        file $"agentic-workflows/.github/workflows/{w.Name}.md" (workflowMarkdown p w)
    for a in p.Agents |> List.filter (fun a -> p.Workflows |> List.exists (fun w -> w.Agent = a.Name)) do
        file $"agentic-workflows/.github/agents/{a.Name}.md" (profile p a)
    let defaults =
        p.AgenticDefaults @ (if hostIsInternal p then [] else [ "default_otlp_endpoint", p.Host ])
        |> List.distinctBy fst
        // `gh aw env` wants plain integers where frontmatter also accepts K/M suffixes ("2M").
        |> List.map (fun (k, v) ->
            let m = Text.RegularExpressions.Regex.Match(v.Trim(), "^(\d+)([KkMm])$")
            let v = if m.Success then string (int64 m.Groups[1].Value * (if m.Groups[2].Value.ToUpperInvariant() = "K" then 1000L else 1000000L)) else v
            k, v)
        |> List.map (fun (k, v) -> $"{k}: {yamlString v}")
        |> String.concat "\n"
    file "agentic-workflows/aw-defaults.yml" ($"# {banner p}\n" + defaults + "\n")
    file "agentic-workflows/aw-policy.json" (p.AgenticPolicy |> List.map (fun (k, v) -> k, str v) |> objOf |> render)
]

// ---------------------------------------------------------------------------
// Platform host static content: the MCP registry
// ---------------------------------------------------------------------------

let endpoints (p: Platform) (published: DateTimeOffset) = [
    for path, content in registryFiles p.Mcp published do
        file $"endpoints/{path}.json" content
    file "endpoints/hook-rules.json" (render (rulesJson p))
]

// ---------------------------------------------------------------------------
// Workstations: file-based + native MDM + policy hooks
// ---------------------------------------------------------------------------

let mdmValues (pol: Policy) =
    let groups = set [ "permissions"; "sandbox"; "telemetry"; "remoteControl"; "features"; "policyHelper" ]
    let text (n: JsonNode) =
        match n with
        | :? JsonValue as v when v.GetValueKind() = Text.Json.JsonValueKind.String -> v.GetValue<string>()
        | other -> other.ToJsonString()
    [
        for kv in (toJson (flatten pol) :?> JsonObject) do
            match kv.Value with
            | :? JsonObject as g when groups.Contains kv.Key ->
                for inner in g do $"{kv.Key}.{inner.Key}", text inner.Value
            | v -> kv.Key, text v
    ]

let workstation (p: Platform) =
    let pol = resolvedPolicy p
    let json = render (toJson (forFile (flatten pol)))
    let policyHooks = render (hooksJson p "policy-hook" false)
    let mdm = mdmValues pol
    let regEsc (s: string) = s.Replace("\\", "\\\\").Replace("\"", "\\\"")
    let reg =
        "Windows Registry Editor Version 5.00\r\n\r\n[HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\GitHubCopilot]\r\n"
        + (mdm |> List.map (fun (k, v) -> "\"" + k + "\"=\"" + regEsc v + "\"") |> String.concat "\r\n") + "\r\n"
    let psEsc (s: string) = s.Replace("'", "''")
    let ps1 =
        $"# {banner p}\r\n# Intune remediation / ConfigMgr: GitHub Copilot managed settings (native MDM) + machine-wide policy hooks.\r\n"
        + "#Requires -RunAsAdministrator\r\n$ErrorActionPreference = 'Stop'\r\n"
        + "$key = 'HKLM:\\SOFTWARE\\Policies\\GitHubCopilot'\r\nNew-Item -Path $key -Force | Out-Null\r\n$values = [ordered]@{\r\n"
        + (mdm |> List.map (fun (k, v) -> "  '" + k + "' = '" + psEsc v + "'") |> String.concat "\r\n")
        + "\r\n}\r\nforeach ($k in $values.Keys) { New-ItemProperty -Path $key -Name $k -Value $values[$k] -PropertyType String -Force | Out-Null }\r\n"
        + "$policyDir = 'C:\\ProgramData\\GitHub\\Copilot\\policy.d'\r\nNew-Item -ItemType Directory -Force $policyDir | Out-Null\r\n"
        + "@'\r\n" + policyHooks + "'@ | Set-Content -Encoding utf8 (Join-Path $policyDir '00-agent-platform.json')\r\n"
    let xml (s: string) = Security.SecurityElement.Escape s
    let mobileconfig =
        let keys = mdm |> List.map (fun (k, v) -> $"          <key>{xml k}</key><string>{xml v}</string>") |> String.concat "\n"
        let uuid1 = Guid(MD5.HashData(Encoding.UTF8.GetBytes(p.Organization + "/profile")))
        let uuid2 = Guid(MD5.HashData(Encoding.UTF8.GetBytes(p.Organization + "/prefs")))
        $"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>PayloadType</key><string>Configuration</string>
  <key>PayloadIdentifier</key><string>com.{xml p.Organization}.github-copilot</string>
  <key>PayloadUUID</key><string>{uuid1}</string>
  <key>PayloadDisplayName</key><string>GitHub Copilot managed settings ({xml p.Name})</string>
  <key>PayloadVersion</key><integer>1</integer>
  <key>PayloadScope</key><string>System</string>
  <key>PayloadContent</key><array><dict>
    <key>PayloadType</key><string>com.apple.ManagedClient.preferences</string>
    <key>PayloadIdentifier</key><string>com.{xml p.Organization}.github-copilot.preferences</string>
    <key>PayloadUUID</key><string>{uuid2}</string>
    <key>PayloadVersion</key><integer>1</integer>
    <key>PayloadContent</key><dict><key>com.github.copilot</key><dict><key>Forced</key><array><dict>
      <key>mcx_preference_settings</key><dict>
{keys}
      </dict>
    </dict></array></dict></dict>
  </dict></array>
</dict></plist>
"""
    [
        file "workstation/linux/etc/github-copilot/managed-settings.json" json
        file "workstation/linux/etc/github-copilot/policy.d/00-agent-platform.json" policyHooks
        file "workstation/macos/Library/Application Support/GitHubCopilot/managed-settings.json" json
        // hooks-reference "Policy hooks": Linux/macOS both read /etc/github-copilot/policy.d/*.json (root-owned, not group/world-writable).
        file "workstation/macos/etc/github-copilot/policy.d/00-agent-platform.json" policyHooks
        file "workstation/macos/com.github.copilot.mobileconfig" mobileconfig
        file "workstation/windows/GitHubCopilot-policy.reg" reg
        file "workstation/windows/Install-AgentPlatformPolicy.ps1" ps1
        file "workstation/windows/ProgramFiles/GitHubCopilot/managed-settings.json" json
    ]

// ---------------------------------------------------------------------------
// GitHub settings (REST bodies)
// ---------------------------------------------------------------------------

let githubApi (p: Platform) = [
    for r in p.GitHub.Rulesets do
        file $"github/rulesets/{r.Name}.json" (render (rulesetJson r))
    if not p.GitHub.ContentExclusion.IsEmpty then
        file "github/copilot-content-exclusion.json" (render (contentExclusionJson p.GitHub))
    file "github/cloud-agent-permissions.json" (render (cloudAgentPermissionsJson p.GitHub))
    let cloudMcp = p.Mcp.Servers |> List.filter (fun s -> p.Agents |> List.exists (fun a -> List.contains s.Key a.Mcp))
    // GET-only API: this is the configuration every repository is expected to have; `plan` compares against it.
    file "github/cloud-agent-expected-configuration.json" (render (cloudAgentConfigJson p.GitHub (Some(cloudAgentConfig cloudMcp))))
    file "github/agents-variables.json" (p.GitHub.AgentVariables |> List.map (fun (k, v) -> k, str v) |> objOf |> render)
    file "github/organization-custom-instructions.md" (organizationInstructions p.Standards + "\n")
    file "github/mcp-policy.json" (
        obj [
            "mcp_servers_in_copilot", Some(str "enabled")
            "mcp_registry_url", p.Mcp.RegistryUrl |> Option.orElse (Some $"{p.Host}") |> Option.map str
            "restrict_mcp_access_to_registry", Some(str (match p.Mcp.RegistryMode with RegistryOnly -> "registry_only" | DiscoveryOnly -> "allow_all"))
        ]
        |> render)
]

// ---------------------------------------------------------------------------
// Coverage: which control reaches which surface, by what mechanism
// ---------------------------------------------------------------------------

let coverage (p: Platform) =
    let surfaces = [ "cli"; "vscode"; "visual-studio"; "jetbrains"; "copilot-app"; "cloud-agent"; "sdk"; "agentic-workflow" ]
    let row (control: string) (cells: (string * string) list) =
        objOf [ "control", str control; "surfaces", (surfaces |> List.map (fun s -> s, str (cells |> List.tryFind (fst >> (=) s) |> Option.map snd |> Option.defaultValue ""))) |> objOf ]
    let managed = keysOf (resolvedPolicy p)
    let documentedRows =
        documented
        |> List.filter (fun (k, _) -> managed |> List.exists (fun m -> m = k || m.StartsWith(k + ".")))
        |> List.map (fun (k, clients) ->
            let has (c: string) = clients.Split(' ') |> Array.contains c
            row k [
                if has "CLI" then "cli", "managed-settings"
                if has "VSCode" then "vscode", "managed-settings"
                if has "App" then "copilot-app", "managed-settings"
                if has "JetBrains" then "jetbrains", "managed-settings"
                if has "CloudAgent" then "cloud-agent", "managed-settings"
                if k.StartsWith "permissions" || k = "model" || k = "telemetry" then "sdk", "SessionConfig"
                if k = "model" || k = "telemetry" then "agentic-workflow", "gh aw env defaults"
                if k = "enabledPlugins" then "agentic-workflow", "plugins: frontmatter"
                if k = "enabledPlugins" then "sdk", "PluginDirectories"
            ])
    arr [
        yield! documentedRows
        row "mcp-registry" [ "cli", "registry v0.1"; "vscode", "registry v0.1"; "visual-studio", "registry v0.1"; "jetbrains", "registry v0.1"; "copilot-app", "registry v0.1" ]
        row "mcp (cloud agent)" [ "cloud-agent", "repository MCP configuration + COPILOT_MCP_ secrets"; "agentic-workflow", "mcp-servers: frontmatter"; "sdk", "SessionConfig.McpServers" ]
        row "hooks (enforce)" [ "cli", "policy.d + plugin (exec curl.exe, fail-closed)"; "vscode", ".github/hooks (curl, fail-closed)"; "cloud-agent", ".github/hooks (bash curl, fail-closed)"; "sdk", "SessionHooks (in-process)"; "copilot-app", "plugin hooks" ]
        row "hooks (capture)" [ "cli", "http"; "vscode", "http"; "copilot-app", "http"; "cloud-agent", "http (firewall allowlist)"; "sdk", "in-process"; "agentic-workflow", "OTLP + gh aw logs" ]
        row "standards" [ "cli", "instructions + plugin skills"; "vscode", "instructions + plugin skills"; "visual-studio", "copilot-instructions.md"; "jetbrains", "copilot-instructions.md"; "copilot-app", "plugin skills"; "cloud-agent", "instructions + org instructions"; "sdk", "SystemMessage"; "agentic-workflow", "AGENTS.md + imports" ]
        row "custom agents" [ "cli", ".github-private/agents"; "vscode", ".github-private/agents"; "visual-studio", ".github-private/agents (18.6+)"; "jetbrains", ".github-private/agents"; "copilot-app", ".github-private/agents"; "cloud-agent", ".github-private/agents"; "sdk", "CustomAgents"; "agentic-workflow", "imports: .github/agents" ]
        row "rulesets" [ "cloud-agent", "copilot_code_review, workflows, file_path_restriction"; "agentic-workflow", "required workflows" ]
        row "content exclusion" [ "cli", "org policy"; "vscode", "org policy"; "visual-studio", "org policy"; "jetbrains", "org policy"; "copilot-app", "org policy"; "cloud-agent", "org policy" ]
    ]

// ---------------------------------------------------------------------------
// Everything, with a lock file
// ---------------------------------------------------------------------------

let all (p: Platform) (published: DateTimeOffset) =
    let p = staged p
    let files =
        githubPrivate p @ marketplaceFiles p @ repoBaseline p @ agenticWorkflows p @ endpoints p published @ workstation p @ githubApi p
        @ [ file "coverage.json" (render (coverage p)) ]
    let hash (s: string) = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes s)).ToLowerInvariant()
    let lock =
        objOf [
            "platform", str p.Name
            "organization", str p.Organization
            "version", str p.Version
            "rollout", str (string p.Rollout)
            "files", (files |> List.sortBy _.Path |> List.map (fun f -> f.Path, str (hash f.Content)) |> objOf)
        ]
    files @ [ file "platform.lock.json" (render lock) ]

let writeTo (outDir: string) (files: File list) =
    for f in files do
        let path = Path.Combine(outDir, f.Path)
        Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
        let content = f.Content.Replace("\r\n", "\n")
        let content = if f.Path.EndsWith ".ps1" || f.Path.EndsWith ".reg" then content.Replace("\n", "\r\n") else content
        File.WriteAllText(path, content, UTF8Encoding(false))
    files.Length
